{{- if .Values.createAdminSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchdb.fullname" . }}
  labels:
    app: {{ template "couchdb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  adminUsername: {{ template "couchdb.defaultsecret" .Values.adminUsername }}
  adminPassword: {{ template "couchdb.defaultsecret" .Values.adminPassword }}
  cookieAuthSecret: {{ template "couchdb.defaultsecret" .Values.cookieAuthSecret }}

---

{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backup
  labels:
    app: {{ template "couchdb.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  username: {{ required "target.username for backups must be set!" .Values.backup.target.username | b64enc | quote }}
  password: {{ required "target.password for backups must be set!" .Values.backup.target.password | b64enc | quote }}
  host: {{ required "target.host for backups must be set!" .Values.backup.target.host | b64enc | quote }}