apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "couchdb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "couchdb.serviceaccount" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "couchdb.serviceaccount" . }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "couchdb.serviceaccount" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "couchdb.serviceaccount" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "couchdb.serviceaccount" . }}
    namespace: {{ .Release.Namespace }}